language: node_js
node_js:
- '8.4'
notifications:
  slack:
    secure: lH9XTw1yhodo+78UB3qCx+6WXXcq9/UTnj02MSrzU3wVwofNqkO4wavVxpyeN7S3wGo8xjMxL554UOk/5nqLrMyUL0/KYxSDObLdbUmk/0p7NTSzVdgvDA85Q9ZT7WWS5sSfGWt3cgh6HIsK9KIPTfXaYa/2jqkLzoYUGzLzUI9Hl7eIPRldRpgHl+McBVvqyi60vRf35/1C5vlRJu0EQzQt9BSiBqXXmHO+IUhehooBVzVLNB0M6eK3hHz6W/x0+IqGHQfU6KCGttJovcbdBgXhfxK9Od9TqXHUifKFpC0XN1ZoRUEWspHPbFehoS5iX2DUOuw1awxrat1WuDCDjF4vc5ijLuUvGQ0l0yo1O+yMMGuxaRcSVIC8fqxfKOTObFPkjt9xzRZYAc6V/kzhazBtiVQh2EonnOIu7kLRHon3+NjFzHmo53fRdMJglhU6GX01Em/KXzUySQdpw5VZVTQVyvw71PxOLxIwCmaudDW3MDOKxALpLOshBmezLysXKF84xzdHdkthfJADklpdVdcWJKCvnN0kYNhbHmF8+gWcgtgjN2enoBc3S1tcn1R77tL66ym2AavVRg3C5dmtROzN2IemIkuCkwSICCT1vDHGLgIPPMCCt0WWz6nbzqeLqI1H2WnzWuDFhiImEMOfRQ3DL7cSfcWBHDtPq3XWenE=
  on_success: never
  on_failure: always